name: Enable Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            try {
              await github.rest.pulls.enableAutoMerge({
                owner,
                repo,
                pull_number: number,
                merge_method: 'squash'
              });
              console.log(`✅ Auto-merge enabled for PR #${number}`);
            } catch (error) {
              console.log(`⚠️ Could not enable auto-merge for PR #${number}: ${error.message}`);
            }
