name: deploy-backend

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'

      - name: Stage artifacts (server.js + express-ingest)
        run: |
          set -euo pipefail
          rm -rf artifacts
          mkdir -p artifacts

          # 1) entrypoint at /site/wwwroot/server.js
          if [ -f backend/server.js ]; then cp backend/server.js artifacts/server.js; else cp server.js artifacts/server.js; fi

          # 2) root package.json -> force start, strip postinstall
          if [ -f backend/package.json ]; then
            jq '(.scripts//={}) | .scripts.start="node server.js" | del(.scripts.postinstall)' backend/package.json > artifacts/package.json
            [ -f backend/package-lock.json ] && cp backend/package-lock.json artifacts/package-lock.json || true
          else
            jq '(.scripts//={}) | .scripts.start="node server.js" | del(.scripts.postinstall)' package.json > artifacts/package.json
            [ -f package-lock.json ] && cp package-lock.json artifacts/package-lock.json || true
          fi

          # 3) choose the real express-ingest (must have helper + src or dist)
          for d in backend/express-ingest CanadWill_Phase2/express-ingest express-ingest; do
            if [ -d "$d" ] && [ -f "$d/serp-tools.runtime.js" ] && { [ -d "$d/src/providers" ] || [ -d "$d/dist/providers" ]; }; then
              EXPRESS_SRC="$d"; break
            fi
          done
          test -n "${EXPRESS_SRC:-}" || { echo "ERROR: express-ingest with helper+(src|dist) not found"; exit 1; }

          mkdir -p artifacts/express-ingest
          cp -a "$EXPRESS_SRC"/. artifacts/express-ingest/

          echo "STAGED TREE (first 3 levels):"
          find artifacts -maxdepth 3 -print

      - name: Install root deps
        run: |
          set -e
          cd artifacts
          npm install --omit=dev --no-audit --no-fund

      - name: Install & build express-ingest (produce dist/)
        run: |
          set -e
          cd artifacts/express-ingest
          npm install --omit=dev --no-audit --no-fund || true
          npm install --no-save typescript@5 @types/node @types/express
          if [ -f tsconfig.json ]; then
            node ./node_modules/typescript/bin/tsc -p tsconfig.json
          fi
          # HARD REQUIREMENTS for this deploy:
          test -f serp-tools.runtime.js || { echo "ERROR: missing express-ingest/serp-tools.runtime.js"; exit 1; }
          test -f dist/providers/serphouseClient.js || { echo "ERROR: missing dist/providers/serphouseClient.js after build"; ls -la dist || true; exit 1; }
          cd -

      - name: Sanitize runtime tree (prevent sub-app detection)
        run: |
          set -e
          # keep built JS, remove sub-app manifests that can confuse startup
          rm -f artifacts/express-ingest/package.json artifacts/express-ingest/package-lock.json artifacts/express-ingest/Procfile
          # assert required runtime files remain
          test -f artifacts/express-ingest/serp-tools.runtime.js
          test -f artifacts/express-ingest/dist/providers/serphouseClient.js

      - name: Create deploy.zip (exclude root Procfile)
        run: |
          set -e
          cd artifacts
          zip -r ../deploy.zip . -x "**/.git/**" "**/.cache/**" "**/node_modules/.cache/**" "Procfile"
          cd -

      - name: Deploy to Azure WebApp (ingest)
        uses: azure/webapps-deploy@v3
        with:
          app-name: canadawill-ingest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip