name: deploy-backend

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'

      # Stage a clean artifacts folder (this becomes /home/site/wwwroot)
      - name: Stage backend into flat artifacts root
        run: |
          set -e
          rm -rf artifacts
          mkdir -p artifacts
          # Flatten server.js & root manifests
          cp backend/server.js artifacts/server.js
          if [ -f backend/package.json ]; then cp backend/package.json artifacts/package.json; fi
          if [ -f backend/package-lock.json ]; then cp backend/package-lock.json artifacts/package-lock.json; fi
          # Copy express-ingest without rsync (robust on GH runners)
          if [ -d backend/express-ingest ]; then
            mkdir -p artifacts/express-ingest
            cp -a backend/express-ingest/. artifacts/express-ingest/
          fi
          echo "===== STAGED TREE (first 3 levels) ====="
          find artifacts -maxdepth 3 -type d -print
          echo "===== ROOT LIST ====="
          ls -la artifacts
          echo "===== EXPRESS-INGEST LIST ====="
          ls -la artifacts/express-ingest || true

      - name: Install root deps
        run: |
          set -e
          cd artifacts
          if [ -f package.json ]; then
            npm install --omit=dev
          fi

      - name: Install & build express-ingest deps
        run: |
          set -e
          if [ -f artifacts/express-ingest/package.json ]; then
            cd artifacts/express-ingest
            npm install --omit=dev
            if [ -f tsconfig.json ]; then npx tsc -p tsconfig.json || true; fi
            cd -
          fi

      - name: Create deploy.zip
        run: |
          set -e
          cd artifacts
          zip -r ../deploy.zip . -x "**/.git/**" "**/.cache/**" "**/node_modules/.cache/**"
          cd -

      - name: Deploy to Azure WebApp (ingest)
        uses: azure/webapps-deploy@v3
        with:
          app-name: canadawill-ingest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip
