name: deploy-backend

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch: {}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (backend)
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (backend)
        working-directory: backend
        run: npm run build --if-present

      - name: Zip artifact (backend)
        run: |
          cd backend
          zip -r ../backend-artifact.zip . \
            -x "node_modules/**" \
            -x "**/*.map"
          ls -lh ../backend-artifact.zip

      - name: Deploy to Azure Web App (backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: canadawill-ingest-ave2f8fjcxeuaehz
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BACKEND }}
          package: backend-artifact.zip
