name: deploy-ingest

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch: {}

jobs:
  deploy-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (express-ingest)
        working-directory: backend/express-ingest
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (express-ingest)
        working-directory: backend/express-ingest
        run: npm run build --if-present

      - name: Zip artifact (express-ingest)
        run: |
          cd backend/express-ingest
          zip -r ../../express-ingest-artifact.zip . \
            -x "node_modules/**" \
            -x "**/*.map"
          ls -lh ../../express-ingest-artifact.zip

      - name: Deploy to Azure Web App (express-ingest)
        uses: azure/webapps-deploy@v2
        with:
          app-name: canadawill-ingest-ave2f8fjcxeuaehz
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BACKEND }}
          package: express-ingest-artifact.zip
